inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 285
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'spec/models/box_request_spec.rb'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'define', 'setup']